const lessonsData = {
    "lesson6": {
        title: "درس ۶",
        words: [
            { en: "breadwinner", pron: "بِرِد وینِر", fa: "نان‌آور", difficulty: "hard" },
            { en: "obligatory", pron: "اُبلیگِتوری", fa: "اجباری", difficulty: "hard" },
            { en: "tuition", pron: "تیوئیشِن", fa: "شهریه / آموزش / تعلیم", difficulty: "hard" },
            { en: "afford", pron: "اِفورد", fa: "بضاعت داشتن / از عهده بر آمدن", difficulty: "easy" },
            { en: "relevance", pron: "رِلِوِنس", fa: "ربط / ارتباط", difficulty: "hard" },
            { en: "extended families", pron: "اِکس تِندید فَمِلیز", fa: "خانواده‌های گسترده", difficulty: "easy" },
            { en: "irritability", pron: "ایریتِبیلیتی", fa: "کج‌خلقی / حساسیت / زودرنجی", difficulty: "hard" },
            { en: "vocalize", pron: "وُکالایز", fa: "صدا زدن / سروصدا کردن", difficulty: "hard" },
            { en: "clerical", pron: "کِلِریکال", fa: "دفتری / مربوط به منشی‌گری / روحانی", difficulty: "hard" },
            { en: "schedules", pron: "اِسکِجولز", fa: "برنامه / زمانبندی", difficulty: "easy" },
            { en: "glances", pron: "گِلَنسِز", fa: "نگاه اجمالی / نگاه انداختن", difficulty: "easy" },
            { en: "images", pron: "ایماِجِز", fa: "وجهه / تصویر", difficulty: "easy" },
            { en: "occupy", pron: "آکیوپای", fa: "اشغال کردن / مشغول کردن / تصرف کردن", difficulty: "easy" },
            { en: "executive", pron: "اِگزِکیوتیو", fa: "مدیر / قوه مجریه / اجرایی", difficulty: "hard" },
            { en: "obstacle", pron: "آبستِکِل", fa: "مانع / سد / مشکل", difficulty: "hard" },
            { en: "previously", pron: "پریویِسلی", fa: "قبلاً", difficulty: "easy" },
            { en: "combine", pron: "کامباین", fa: "ترکیب کردن", difficulty: "easy" },
            { en: "chore", pron: "چُر", fa: "کار عادی و روزانه", difficulty: "easy" },
            { en: "capable", pron: "کِیپِبِل", fa: "توانا / با استعداد", difficulty: "easy" },
            { en: "laundry", pron: "لاندری", fa: "لباس شستن / لباس‌شویی", difficulty: "easy" },
            { en: "employed", pron: "ایمپلُید", fa: "شاغل", difficulty: "easy" },
            { en: "employer", pron: "ایمپلُیِر", fa: "کارفرما", difficulty: "easy" },
            { en: "employ", pron: "ایمپلُی", fa: "استخدام کردن / به کار بردن", difficulty: "easy" },
            { en: "necessitates", pron: "نِسِسیتِیتس", fa: "مستلزم بودن / ضروری ساختن", difficulty: "hard" },
            { en: "engineer", pron: "اِنجینیر", fa: "مهندس", difficulty: "easy" },
            { en: "politician", pron: "پالیتیشِن", fa: "سیاستمدار", difficulty: "easy" },
            { en: "lawyer", pron: "لایِر", fa: "وکیل", difficulty: "easy" },
            { en: "glass ceiling", pron: "گِلَس سیلینگ", fa: "سقف شیشه‌ای (موانع نامرئی ارتقاء زنان)", difficulty: "hard" },
            { en: "Monetary", pron: "مانیتِری", fa: "مالی", difficulty: "hard" },
            { en: "seek", pron: "سیک", fa: "جستجو کردن / طلب کردن", difficulty: "easy" },
            { en: "creative", pron: "کریئِیتیو", fa: "خلاق", difficulty: "easy" },
            { en: "raising", pron: "رِیزینگ", fa: "بلند کردن / پرورش دادن / بزرگ کردن", difficulty: "easy" },
            { en: "reveal", pron: "ریویل", fa: "آشکار کردن", difficulty: "hard" },
            { en: "radically", pron: "رَدیکِلی", fa: "به طور اساسی", difficulty: "hard" },
            { en: "portray", pron: "پُرترِی", fa: "به تصویر کشیدن / در نقش کسی ظاهر شدن", difficulty: "hard" },
            { en: "advertising", pron: "اَدوِرتایزینگ", fa: "تبلیغات", difficulty: "easy" },
            { en: "exclusive", pron: "اِکسکلوسیو", fa: "اختصاصی / انحصاری", difficulty: "hard" },
            { en: "Industrial", pron: "اینداستریال", fa: "صنعتی", difficulty: "easy" },
            { en: "Revolution", pron: "رِوِلوشِن", fa: "انقلاب", difficulty: "easy" },
            { en: "variation", pron: "وِریئِیشِن", fa: "اختلاف / تغییر", difficulty: "hard" },
            { en: "informal", pron: "اینفُرمال", fa: "غیررسمی", difficulty: "easy" },
            { en: "productive", pron: "پروداکتیو", fa: "پربازده", difficulty: "hard" },
            { en: "Individual", pron: "ایندیویدجوال", fa: "انفرادی / فرد / شخص", difficulty: "easy" },
            { en: "wealthy", pron: "وِلثی", fa: "ثروتمند", difficulty: "easy" },
            { en: "nanny", pron: "نَنی", fa: "پرستار بچه", difficulty: "easy" },
            { en: "trend", pron: "تِرِند", fa: "روند / جریان / مد", difficulty: "easy" },
            { en: "emerged", pron: "ای مِرجِد", fa: "بیرون آمدن / آشکار شدن / به وجود آمدن", difficulty: "hard" },
            { en: "responsibilities", pron: "ریسپانسیبیلیتیز", fa: "وظایف", difficulty: "easy" },
            { en: "arrange", pron: "اِرِینج", fa: "مقرر کردن / مرتب کردن", difficulty: "easy" },
            { en: "establish", pron: "اِستَبلیش", fa: "تاسیس کردن / برقرار کردن / ثابت کردن", difficulty: "hard" },
            { en: "secure", pron: "سِکیور", fa: "مطمئن / محکم / تامین کردن / محکم بستن", difficulty: "easy" },
            { en: "fairly", pron: "فِرلی", fa: "نسبتاً / منصفانه", difficulty: "easy" },
            { en: "rare", pron: "رِر", fa: "نادر / نیمه‌پخته", difficulty: "easy" },
            { en: "survey", pron: "سِروِی", fa: "پژوهش / بررسی کردن / نظرسنجی کردن", difficulty: "easy" },
            { en: "significant", pron: "سیگنیفیکِنت", fa: "مهم / چشمگیر", difficulty: "hard" },
            { en: "cultural", pron: "کالچِرال", fa: "فرهنگی", difficulty: "easy" },
            { en: "dramatic", pron: "درَماتیک", fa: "مهیج / نمایشی / چشمگیر", difficulty: "hard" },
            { en: "involvement", pron: "اینوالومِنت", fa: "درگیری / دخالت", difficulty: "hard" },
            { en: "involve", pron: "اینوالو", fa: "شامل بودن / شامل کردن / رابطه داشتن", difficulty: "easy" },
            { en: "decision", pron: "دیسیژِن", fa: "تصمیم", difficulty: "easy" },
            { en: "Financial", pron: "فاینَنشال", fa: "مالی", difficulty: "easy" },
            { en: "insufficient", pron: "اینسافیشِنت", fa: "ناکافی", difficulty: "hard" },
            { en: "grant", pron: "گِرَنت", fa: "اهدا کردن / کمک هزینه (تحصیلی)", difficulty: "hard" },
            { en: "bored", pron: "بُرد", fa: "خسته (کسل)", difficulty: "easy" },
            { en: "tendency", pron: "تِندِنسی", fa: "تمایل / عادت / میل", difficulty: "hard" },
            { en: "earn", pron: "اِرن", fa: "به دست آوردن / پول در آوردن", difficulty: "easy" },
            { en: "revolutionized", pron: "رِوِلوشِنایزد", fa: "منقلب / متحول / دگرگون", difficulty: "hard" },
            { en: "critical", pron: "کریتیکال", fa: "بحرانی / انتقادی / منتقدانه", difficulty: "hard" },
            { en: "skeptical", pron: "اِسکِپتیکال", fa: "شک‌گرایانه", difficulty: "hard" },
            { en: "event", pron: "ایوِنت", fa: "اتفاق / حادثه / رویداد", difficulty: "easy" },
            { en: "revealed", pron: "ریویلد", fa: "آشکار", difficulty: "hard" },
            { en: "occupied", pron: "آکیوپاید", fa: "مشغول / اشغال شده", difficulty: "hard" },
            { en: "portrayed", pron: "پُرترِید", fa: "به تصویر کشیدن / در نقش کسی ظاهر شدن", difficulty: "hard" },
            { en: "facilitated", pron: "فَسیلیتِیتِد", fa: "تسهیل کردن", difficulty: "hard" },
            { en: "vary", pron: "وِری", fa: "متفاوت بودن / تنوع دادن / تغییر کردن", difficulty: "easy" },
            { en: "fluctuate", pron: "فِلَکچوئِیت", fa: "نوسان داشتن", difficulty: "hard" },
            { en: "emerge", pron: "ای مِرج", fa: "بیرون آمدن / فاش شدن / به وجود آمدن", difficulty: "hard" },
            { en: "denying", pron: "دینایینگ", fa: "تکذیب کردن / رد کردن / محروم کردن", difficulty: "easy" },
            { en: "removing", pron: "ریمووینگ", fa: "در آوردن / برکنار کردن / حذف کردن", difficulty: "easy" },
            { en: "ignoring", pron: "ایگنُرینگ", fa: "بی‌توجهی کردن / نادیده گرفتن", difficulty: "easy" },
            { en: "seeking", pron: "سیکینگ", fa: "به دنبال گشتن / جستجو کردن / طلب کردن", difficulty: "easy" },
            { en: "lethal", pron: "لیتال", fa: "مهلک / کشنده / مرگبار", difficulty: "hard" },
            { en: "immediate", pron: "ایمیدیت", fa: "فوری", difficulty: "easy" },
            { en: "adequate", pron: "اَدِکویت", fa: "کافی", difficulty: "hard" },
            { en: "private", pron: "پرایوِت", fa: "خصوصی / محرمانه", difficulty: "easy" },
            { en: "blended", pron: "بِلِندِد", fa: "ترکیبی", difficulty: "easy" },
            { en: "relative", pron: "رِلِتیو", fa: "خویشاوند / نسبی / نسبت به", difficulty: "easy" },
            { en: "necessity", pron: "نِسِسیتی", fa: "نیاز / وسیله ضروری / اجبار / ضرورت", difficulty: "hard" },
            { en: "combination", pron: "کامبینِیشِن", fa: "ترکیب", difficulty: "easy" },
            { en: "shared", pron: "شِرد", fa: "تقسیم کردن / سهیم بودن / در میان گذاشتن", difficulty: "easy" },
            { en: "necessitated", pron: "نِسِسیتِیتِد", fa: "ایجاب کردن / مجبور کردن / مستلزم بودن", difficulty: "hard" },
            { en: "former", pron: "فُرمِر", fa: "قبلی / سابق / اولی بین دو چیز", difficulty: "hard" },
            { en: "latter", pron: "لَتِر", fa: "آخری / دومی از بین دو چیز", difficulty: "hard" },
            { en: "part-time", pron: "پارت تایم", fa: "نیمه‌وقت / پاره‌وقت", difficulty: "easy" },
            { en: "flex-time", pron: "فِلِکس تایم", fa: "زمان انعطاف‌پذیر", difficulty: "easy" },
            { en: "full-time", mission: "فول تایم", fa: "تمام‌وقت", difficulty: "easy" },
            { en: "overtime", pron: "اووِرتایم", fa: "اضافه‌کاری", difficulty: "easy" },
            { en: "blend", pron: "بِلِند", fa: "مخلوط کردن / ترکیب / مخلوط", difficulty: "easy" }
        ]
    }
};

const examData = {
    "lesson6": {
        "exam1": [
            { q: "The company launched a __ marketing campaign that attracted many customers.", options: ["wealthy", "creative", "rare", "secure"], ans: 1 },
            { q: "Parents are responsible for __ their children properly.", options: ["raising", "portraying", "arranging", "surveying"], ans: 0 },
            { q: "The report will __ the truth about the accident.", options: ["reveal", "involve", "secure", "establish"], ans: 0 },
            { q: "Technology has __ changed the way we communicate.", options: ["fairly", "informally", "radically", "culturally"], ans: 2 },
            { q: "The actor was able to __ the character perfectly.", options: ["secure", "portray", "arrange", "raise"], ans: 1 },
            { q: "Television __ influences people's buying decisions.", options: ["variation", "revolution", "advertising", "survey"], ans: 2 },
            { q: "This club offers __ services for its members only.", options: ["productive", "exclusive", "dramatic", "informal"], ans: 1 },
            { q: "The city became an important __ center.", options: ["industrial", "wealthy", "cultural", "individual"], ans: 0 },
            { q: "The Internet caused a __ in communication.", options: ["variation", "decision", "revolution", "responsibility"], ans: 2 },
            { q: "There is a slight __ in color between the two products.", options: ["variation", "trend", "survey", "involvement"], ans: 0 }
        ],
        "exam2": [
            { q: "We had an __ discussion with our friends.", options: ["secure", "informal", "exclusive", "significant"], ans: 1 },
            { q: "She is very __ and always finishes her work on time.", options: ["productive", "dramatic", "wealthy", "rare"], ans: 0 },
            { q: "Every __ has different goals and interests.", options: ["revolution", "individual", "survey", "variation"], ans: 1 },
            { q: "The __ businessman donated a large amount of money.", options: ["informal", "wealthy", "productive", "radical"], ans: 1 },
            { q: "They hired a __ to take care of the baby.", options: ["nanny", "surveyor", "advertiser", "actor"], ans: 0 },
            { q: "Online shopping has become a popular __ in recent years.", options: ["trend", "decision", "variation", "involvement"], ans: 0 },
            { q: "New problems __ after the policy was implemented.", options: ["arranged", "emerged", "secured", "portrayed"], ans: 1 },
            { q: "One of your main __ is to complete the project on time.", options: ["surveys", "responsibilities", "variations", "revolutions"], ans: 1 },
            { q: "We need to __ a meeting for next week.", options: ["arrange", "reveal", "involve", "raise"], ans: 0 },
            { q: "The organization was __ in 1995.", options: ["established", "emerged", "surveyed", "portrayed"], ans: 0 }
        ],
        "exam3": [
            { q: "Make sure to __ all the doors before leaving.", options: ["establish", "secure", "reveal", "portray"], ans: 1 },
            { q: "The exam was __ difficult for most students.", options: ["fairly", "radically", "dramatically", "exclusively"], ans: 0 },
            { q: "Finding such a flower is very __.", options: ["productive", "significant", "rare", "cultural"], ans: 2 },
            { q: "A recent __ showed that most people prefer online learning.", options: ["survey", "trend", "variation", "revolution"], ans: 0 },
            { q: "She made a __ contribution to the success of the project.", options: ["dramatic", "informal", "significant", "individual"], ans: 2 },
            { q: "Music is an important part of our __ heritage.", options: ["cultural", "industrial", "secure", "productive"], ans: 0 },
            { q: "There was a __ increase in sales after the advertisement.", options: ["wealthy", "dramatic", "rare", "informal"], ans: 1 },
            { q: "His active __ in the project helped the team succeed.", options: ["involvement", "variation", "survey", "revolution"], ans: 0 },
            { q: "This job will __ working with many different people.", options: ["reveal", "involve", "secure", "establish"], ans: 1 },
            { q: "After careful consideration, she made the final __.", options: ["trend", "decision", "responsibility", "variation"], ans: 1 }
        ]
    }
};